name: EZ-DNS 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GCC
      run: |
        choco install mingw

    - name: Build executable
      run: |
        gcc EZ-DNS.c resource.o -lws2_32 -liphlpapi -o EZ-DNS.exe

    - name: Verify executable
      run: |
        if (Test-Path -Path "EZ-DNS.exe") {
          Write-Host "Build successful: EZ-DNS.exe exists."
        } else {
          Write-Host "Build failed: EZ-DNS.exe not found."
          exit 1
        }

    - name: Store Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: EZ-DNS-executable
        path: EZ-DNS.exe
